### ISSUE TITLE
How to handle ambiguous bases during RTD calculation?

### ISSUE THREAD

**Issue by nitinnarwade** [pandurang-kolekar/rtd-phylogeny#1]
Hello Sir,

Thank you for the algorithm and its easy-to-use implementation. 

I am using it in my project, however, in my input sequence, there are a few ambiguous bases. Do you have any suggestions on handling them during RTD calculation?

One way I can think of is to use the possible combinations (N => A/T/G/C/; R => A/G etc.), but is it advisable to use such approach?

Thanks and Regards,
Nitin N.

**Comment by pandurang-kolekar** [comment]
Hi Nitin,

Thanks for using RTD-based method in your project.

The current implementation does not handle ambiguous bases. If we choose to designate them as separate base letters (N, R, etc.), this will further increase the number of combinations of k-mers.  So, even if sequence has any ambiguous bases, method calculates return times only for the standard bases, and associated k-mers.

However, users can customise the set of bases/kmers and still calculate RTDs, not sure how meaningful that will be though.
